site_name: Kĩ năng mềm - Khu học mở
site_description: Cải thiện khá nhiều kĩ năng trong cuộc sống hàng ngày.
site_author: duykhanh471
repo_name: Chỉnh sửa trang
repo_url: https://github.com/daihocmo/ki-nang

nav:
  - 'Trang chủ': 'index.md'
  - 'Nội trợ': 
    - 'Hướng dẫn chính': 'noi-tro/index.md'
    - 'Chăm sóc bản thân': 'noi-tro/cham-soc-ban-than/ban-than.md'
    - 'Chăm sóc gia đình': 'noi-tro/cham-soc-gia-dinh/untitled.md'
    - 'Chăm sóc cây cảnh': 'noi-tro/cham-soc-nha-cua/cham-soc-cay-canh.md'
    - 'Hướng dẫn chính': 'noi-tro/don-dep/huong-dan-chinh.md'
    - 'Tư duy dọn dẹp': 'noi-tro/don-dep/tu-duy-don-dep.md'
    - 'Giặt giũ': 'noi-tro/lam-viec-nha/giat-giu.md'
    - 'Rửa bát': 'noi-tro/lam-viec-nha/rua-bat.md'
  - 'Nấu ăn': 'nau-an/index.md'
  - 'Con trai học': 
    - 'Tổng quan': 'con-trai/index.md'
    - 'Chăm sóc cơ thể': 'con-trai/cach-tam-goi.md'
    - 'Xử lý mùi cơ thể': 'con-trai/mui-co-the.md'
    - 'Chăm sóc da': 'con-trai/skincare.md'
  - 'Bản thân':
    - 'Hướng dẫn chính': 'ban-than/guide.md'
    - 'Thử thách 30 ngày': 'ban-than/30ngay.md'
    - '60 thử thách đại học': 'ban-than/60-thu-thach-dai-hoc.md'
    - 'Chăm sóc bản thân': 'ban-than/ban-than.md'
    - 'Bảo mật riêng tư': 'ban-than/bao-mat-rieng-tu.md'
    - 'Đọc sách': 'ban-than/doc-sach.md'
    - 'Grooming': 'ban-than/grooming.md'
    - 'Trở thành người nghe': 'ban-than/nguoi-nghe.md'
    - 'Thể dục': 'ban-than/the-duc.md'
    - 'Thói quen': 'ban-than/thoi-quen.md'
    - 'Thói quen nhỏ': 'ban-than/tiny-habit.md'
 
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  
plugins:
  - search
  - open-in-new-tab

extra:
  generator: false