site_name: Kĩ năng sống - Khu học mở
site_description: Một cuốn sổ tay về kĩ năng sống và công cuộc tự lập cho mọi người!
site_author: duykhanh471
site_url: https://daihocmo.github.io
repo_name: Đóng góp & chỉnh sửa trang
repo_url: https://github.com/daihocmo/ki-nang-song

nav:
  - 'Trang chủ': 'index.md'
  - 'Chăm sóc cơ thể mỗi ngày':
    - 'Đánh răng': 'cham-soc-ca-nhan/danh-rang.md'
    - 'Rửa mặt và chăm sóc da': 'cham-soc-ca-nhan/cham-soc-da.md'
    - 'Vệ sinh cơ thể': 'cham-soc-ca-nhan/ve-sinh-than-the.md'
    - 'Tóc tai các thứ': 'cham-soc-ca-nhan/toc-tai.md'
    - 'Về mùi cơ thể': 'cham-soc-ca-nhan/khu-mui-co-the.md'
  - 'Trang phục và vệ sinh cá nhân':
    - 'Phối đồ': 've-sinh-trang-phuc/phoi-do.md'
    - 'Phối đồ - Đơn giản hóa cho nam': 've-sinh-trang-phuc/phoi-do-don-gian-hoa.md'
    - 'Cách giặt quần áo': 've-sinh-trang-phuc/cach-giat-quan-ao.md'
    - 'Cách gấp và bảo quản quần áo': 've-sinh-trang-phuc/gap-bao-quan-quan-ao.md'
  - 'Việc nhà cơ bản':
    - 'Tư duy dọn dẹp': 'viec-nha/tu-duy-don-dep.md'
    - 'Rửa bát đúng cách': 'viec-nha/rua-bat.md'
    - 'Quét dọn, lau nhà': 'viec-nha/quet-don-lau-nha.md'
  - 'Nấu ăn & Dinh dưỡng':
    - 'Nấu ăn cơ bản': 'nau-an-dinh-duong/nau-an-co-ban.md'
  - 'PHỤ LỤC':
    - 'Gợi ý sách': 'phu-luc/goi-y-sach.md'
    - 'Tài nguyên tham khảo': 'phu-luc/tai-nguyen-tham-khao.md'

theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  
plugins:
  - search
  - open-in-new-tab

extra:
  generator: false